set langmenu=en_US
let $LANG = 'en_US'
filetype off
call pathogen#infect()
filetype plugin indent on
syntax on
set nocompatible

set modelines=0

" TAB OPTIONS
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set relativenumber

let mapleader = ","

nnoremap / /\v
vnoremap / /\v

set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=125
inoremap <F1> <ESC>
vnoremap <F1> <ESC>
nnoremap <F1> <ESC>

nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>
nnoremap <leader>w <C-w>v<C-w>l

nnoremap <leader>o :FufFile<cr>

set backup
set backupdir=c:/vim_tmp,~/vim_tmp
" set backupskip=blaablaa
set directory=c:/vim_tmp,~/vim_tmp
set writebackup

color evening
set guioptions-=T
set guioptions-=m
